# Generated by Django 5.2 on 2025-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='face_image',
            field=models.ImageField(upload_to='user_faces/'),
        ),
    ]
