# Generated by Django 5.2 on 2025-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userimage_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
