# Generated by Django 5.2 on 2025-05-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userimage_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='encoding',
        ),
    ]
